version: 2
jobs:
  deploy:
    docker:
      - image: google/cloud-sdk

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Copy across app.yaml config
          command: ./app.yaml.sh > ./app.yaml
      - run:
          name: Set up gcloud config
          command: |
            echo $GCLOUD_KEY | base64 --decode | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project ${GCLOUD_PROJECT}
      - run:
          name: Deploying to App Engine
          command: gcloud app deploy app.yaml --version 1

workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          name: deploy-backend
          filters:
            branches:
              only: master