version: 2.1
orbs:
  gcp-cli: circleci/gcp-cli@2.1.0
workflows:
  install_and_configure_cli:
    jobs:
      - gcp-cli/install_and_initialize_cli:
          context: myContext
          executor: gcp-cli/default